server:
  port: 8080

spring:
  ################
  #  MySQL
  ################
  datasource:
    url: jdbc:mysql://localhost:3306/sbfuse?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: abcd1234
    db-name: sbfuse
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  ################
  #  Redis
  ################
  cache:
    type: redis
  redis:
    database: 0
    host: localhost
    password:
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    #lettuce客户端
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms