server:
  port: 8443

  ####################
  # SSL
  ####################
  ssl:
    enabled: true
    key-store: sbfuse.keystore
    key-alias: sbfuse
    key-password: abcd1234
    key-store-type: JKS

spring:

  ################
  #  profiles
  ################
  profiles:
    active: dev

  ################
  #  MySQL
  ################
  datasource:
    url: jdbc:mysql://localhost:3306/sbfuse?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: abcd1234
    db-name: sbfuse
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  ################
  #  Redis
  ################
  cache:
    type: redis
  redis:
    database: 0
    host: localhost
    password:
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

    ##################
    #lettuce客户端
    ##################
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms

  ####################
  # thymeleaf模板配置
  ####################
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

  #####################
  # 静态资源缓存策略
  #####################
  resources:
    chain:
      strategy:
        content:
          enabled: false
          paths: /**

#################
# sbfuse应用配置
#################
sbfuse:
  application:
    config:
      encoding: UTF-8
      timeZone: Asia/Shanghai
      dateFormat: yyyy-MM-dd'T'HH:mm:ss:SSSZ
      #是否输出堆栈
      outputExceptionStackTrace: true


####################
# Mybatis-Plus
####################
#mybatis配置
mybatis-plus:
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic_delete_value: Y
    logic_not_delete_value: N
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用


